version: "3"
services:
  webapp:
    build: ./webapp
    container_name: "webapp"
    ports:
    - 80:80
    volumes:
    - ./webapp:/app
  service1:
    build: ./service1
    container_name: "service1"
    ports:
    - 8081:8080
    - 9228:9229
    volumes:
    - ./service1:/app
  service2:
    build: ./service2
    container_name: "service2"
    ports:
    - 8082:8080
    - 9229:9229
    volumes:
    - ./service2:/app
    depends_on:
    - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null --quiet
