version: "3"
services:
  webapp:
    build: ./webapp
    container_name: "webapp"
    ports:
     - 80:80
    volumes:
     - ./webapp:/app
  service1:
    build: ./service1
    container_name: "service1"
    ports:
     - 8081:8080
    volumes:
     - ./service1:/app
  service2:
     build: ./service2
     container_name: "service2"
     ports:
      - 8082:8080
     volumes:
      - ./service2:/app
#  mongo:
#    image: mongo
#    container_name: mongo
#    environment:
#      - MONGO_DATA_DIR=/data/db
#      - MONGO_LOG_DIR=/dev/null
#    volumes:
#      - ./data/db:/data/db
#    ports:
#        - 27017:27017
#    command: mongod --smallfiles --logpath=/dev/null # --quiet